version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      timezone: UTC
      time: "07:00"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      timezone: UTC
      time: "07:00"
    open-pull-requests-limit: 50
    groups:
      playwright:
        patterns:
          - "playwright*"
          - "@playwright/*"
      react:
        patterns:
          - "react*"
          - "@types/react*"
      connect-and-protobuf:
        patterns:
          - "@connectrpc/*"
          - "@bufbuild/proto*"
      build:
        patterns:
          - "typescript"
          - "esbuild"
          - "tsx"
          - "ts-node"
          - "@types/node"
          - "turbo"
          - "@bufbuild/buf"
          - "jasmine"
          - "@types/jasmine"
      lint-and-format:
        patterns:
          - "@typescript-eslint/*"
          - "eslint-*"
          - "eslint"
          - "@bufbuild/license-header"
          - "prettier"
          - "@arethetypeswrong/*"
